config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'tourings/index'
  devise_for :users
  root to: "tourings#index"
  resources :tourings do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :tourings
end

app/models/displacement.rb
class Displacement < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '~250cc' },
    { id: 3, name: '250~400cc' },
    { id: 4, name: '500cc~' },
    { id: 5, name: '400cc~' },
    { id: 6, name: '250cc~' }
  ]

  include ActiveHash::Associations
  has_many :tourings

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :touring
  belongs_to :user

  validates_uniqueness_of :touring_id, scope: :user_id
end

app/models/style.rb
class Style < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ゆったり景色を楽しみながら' },
    { id: 3, name: 'スポーツライディング' },
    { id: 4, name: '林道,オフロード' }
  ]

  include ActiveHash::Associations
  has_many :tourings
end

app/models/term.rb
class Term < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '半日' },
    { id: 3, name: '1日' },
    { id: 4, name: '2~3日' },
    { id: 5, name: '3日~'}
  ]

  include ActiveHash::Associations
  has_many :tourings
  
end

app/models/touring.rb
class Touring < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :displacement
  belongs_to :style
  belongs_to :term
  belongs_to :area

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  

  with_options presence: true do
    validates :plan
    validates :text
    validates :day
  end

  with_options numericality: { other_than: 1 } do
    validates :displacement_id
    validates :style_id
    validates :term_id
    validates :area_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tourings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tourings, through: :likes, source: :touring

  with_options presence: true do
  validates :nickname
  validates :birthday
  end

  def already_liked?(touring)
    self.likes.exists?(touring_id: touring.id)
  end

  mount_uploader :user_icon, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday, :user_icon])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(touring_id: params[:touring_id])
    redirect_to root_path
  end

  def destroy
    @like = Like.find_by(touring_id: params[:touring_id], user_id: current_user.id)
    @like.destroy
    redirect_to root_path
  end
end

app/controllers/tourings_controller.rb
class TouringsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :touring_find, except: [:index, :new, :create]
  before_action :redirect, only: [:edit, :update, :destroy]
  
  def index
    @tourings = Touring.order('created_at DESC')
    # @user = User.find(params[:id])
    # if @user.user_icon.file != nil
    #   @user_icon = @user.user_icon.url
    # else
    #   @user_icon = 'rider.png'
    # end
  end

  def new
    @touring = Touring.new
    # @touring.users << current_user
  end

  def create
    @touring = Touring.create(touring_params)
    @touring.user_id = current_user.id
    if @touring.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @touring.update(touring_params)
      redirect_to touring_path
    else
      render :edit
    end
  end

  def destroy
    @touring.destroy
    redirect_to root_path
  end


  private

  # def touring_params
  #   params.require(:touring).permit(:plan, :displacement_id, :text, :style_id, :term_id, :area_id, :day).merge(user_id: current_user.id)
  # end

  def touring_params
    params.require(:touring).permit(:plan, :displacement_id, :text, :style_id, :term_id, :area_id, :day)
  end

  def touring_find
    @touring = Touring.find(params[:id])
  end

  def redirect
    redirect_to action: :index unless current_user.id == @touring.user_id
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @tourings = @user.tourings

    if @user.user_icon.file != nil
      @user_icon = @user.user_icon.url
    else
      @user_icon = 'rider.png'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tourings_helper.rb
module TouringsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourists2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__nav"> 
    <%= link_to image_tag("logo.png", class: :footer__logo), root_path %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="heading">
    <div class="top__nav">
      <div class="nav__left">
        <%= link_to image_tag("logo.png", class: :logo), root_path %>
      </div>
      <% if user_signed_in? %>

        <div class="nav__right">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
          <%= link_to "募る", new_touring_path, class: :nav__btn %>
        </div> 
      
      <% else %>
      
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
        </div>
      
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<div class="second-header">
  <div class="second__nav"> 
    <%= link_to image_tag("logo.png", class: :second__logo), root_path %>
  </div>
</footer>

app/views/tourings/_touring.html.erb
<div class="card">
  <div class= "card__body">
    <%= link_to touring.plan, touring_path(touring.id), class: :card__title %>
    <p class= "card__summary">
      <%= "内容: #{touring.text}" %>
    </p>
    <p class= "liked__count">
      (<%= touring.liked_users.count %>)いいね
    </p>
    <%= link_to "by #{touring.user.nickname}", user_path(touring.user.id), class: :card__user %>
  </div>
</div>

app/views/tourings/edit.html.erb
<div class="rides-plan-contents">
  

  <%= render "shared/second-header" %>

  <div class="rides-plan-main">
    <h2 class="rides-plan-title">ツーリングプランを入力</h2>

    <%= form_with(model: @touring, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-rides">
      <div class="weight-bold-text">
        プラン名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :plan, class:"rides-text", id:"ride-name", placeholder:"プラン名（必須 30文字まで)", maxlength:"30" %>
      <div class="rides-explain">
        <div class="weight-bold-text">
          プランの内容、詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"rides-text", id:"ride-info", placeholder:"プランの内容や集合場所の詳細ついて（必須 1,000文字まで）（提案や、注意点など）例）葛西臨海公園集合で、熱海あたりを目指したいです。すり抜け等は行わず、安全第一でゆったりとしたツーリングにしたいです。美味しそうなラーメン屋にもいきたいですね。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    
    <div class="weight-bold-text">希望の条件</div>

    <div class="rides-conditions">
      <div class="form">
        <div class="weight-bold-text">
          排気量
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:displacement_id, Displacement.all, :id, :name, {}, {class:"select-box", id:"ride-displacement"}) %>
        <div class="weight-bold-text">
          ツーリングスタイル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:style_id, Style.all, :id, :name, {}, {class:"select-box", id:"ride-style"}) %>
        <div class="weight-bold-text">
          日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:term_id, Term.all, :id, :name, {}, {class:"select-box", id:"ride-term"}) %>
        <div class="weight-bold-text">
          開催地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"ride-area"}) %>
        <div class="weight-bold-text">
          開催日
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_field :day, class:"rides-day", id:"rides-date" %>
      </div>
    </div>

    <div class="post-btn-content">
      <%= f.submit "更新する", class:"post-btn" %>
    </div>
  </div>
  <% end %>

</div>
<%= render "shared/footer" %>

app/views/tourings/index.html.erb
<%= render "shared/header" %>

<div class="contents">
  <div class="first-view">
  
  </div>

  <% if user_signed_in? %>
    <div class = login_rider>
      <%# <%= image_tag("rider.png", class: :rider_logo) %> 
      <% if current_user.user_icon.file != nil%>
        <%= image_tag current_user.user_icon.url, class:"my_icon" %>
      <% else %>
        <%= image_tag 'rider.png', class:"my_icon" %>
      <% end %>
      <%= link_to (current_user.nickname), user_path(current_user.id), class: :login_user %>
    </div>
  <% end %>
  
  <div class="ride-contents">
    <h2 class="heading-name">ツーリングプラン一覧</h2>
    <div class="top-posts">
      <%= render partial: 'touring', collection: @tourings %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/tourings/new.html.erb
<%= render "shared/second-header" %>

<div class="rides-plan-contents">
  <div class="rides-plan-main">
  <h2 class="rides-plan-title">ツーリングプランを入力</h2>

  <%= form_with(model: @touring, local: true) do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="new-rides">
    <div class="weight-bold-text">
      プラン名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :plan, class:"rides-text", id:"ride-name", placeholder:"プラン名（必須 30文字まで)", maxlength:"30" %>
    <div class="rides-explain">
      <div class="weight-bold-text">
        プランの内容、詳細
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"rides-text", id:"ride-info", placeholder:"プランの内容や集合場所の詳細ついて（必須 1,000文字まで）（提案や、注意点など）例）葛西臨海公園集合で、熱海あたりを目指したいです。すり抜け等は行わず、安全第一でゆったりとしたツーリングにしたいです。美味しそうなラーメン屋にもいきたいですね。" ,rows:"7" ,maxlength:"1000" %>
    </div>
  </div>
    
    
    <div class="weight-bold-text">希望の条件</div>

    <div class="rides-conditions">
      <div class="form">
        <div class="weight-bold-text">
          排気量
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:displacement_id, Displacement.all, :id, :name, {}, {class:"select-box", id:"ride-displacement"}) %>
        <div class="weight-bold-text">
          ツーリングスタイル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:style_id, Style.all, :id, :name, {}, {class:"select-box", id:"ride-style"}) %>
        <div class="weight-bold-text">
          日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:term_id, Term.all, :id, :name, {}, {class:"select-box", id:"ride-term"}) %>
        <div class="weight-bold-text">
          開催地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"ride-area"}) %>
        <div class="weight-bold-text">
          開催日
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_field :day, class:"rides-day", id:"rides-date" %>
      </div>
    </div>

    <div class="post-btn-content">
      <%= f.submit "投稿する", class:"post-btn" %>
    </div>
  </div>
  <% end %>

</div>
<%= render "shared/footer" %>

app/views/tourings/show.html.erb
<%= render "shared/header" %>

<div class="inner">
  <div class="ride__wrapper">
    <p class="ride__hedding">
      <%= @touring.plan %>
    </p>

    
    <div class="ride__body">
      <div class="ride__detail">
        <p class="detail__title">内容</p>
        <p class="detail__message">
          <%= @touring.text %>
        </p>
      </div>
      <div class="ride__detail">
        <p class="detail__title">排気量</p>
        <p class="detail__message">
          <%= @touring.displacement.name %>
        </p>
      </div>
      <div class="ride__detail">
        <p class="detail__title">ツーリングスタイル</p>
        <p class="detail__messages">
          <%= @touring.style.name %>
        </p>
      </div>
      <div class="ride__detail">
        <p class="detail__title">期間</p>
        <p class="detail__messages">
          <%= @touring.term.name %>
        </p>
      </div>
      <div class="ride__detail">
        <p class="detail__title">エリア</p>
        <p class="detail__messages">
          <%= @touring.area.name %>
        </p>
      </div>
      <div class="ride__detail">
        <p class="detail__title">開催日</p>
        <p class="detail__messages">
          <%= @touring.day %>
        </p>
      </div>
      <%= link_to "by #{@touring.user.nickname}", user_path(@touring.user.id), class: :ride__user %>
    </div>


<%# 以下、未実装部分※参加機能を実装しようとして行き詰まった部分
投稿機能と参加機能をまとめてtouringコントローラーで扱う場合、投稿者と参加者が同じ扱いになってしまう。編集、削除、参加の機能の場合分けができない。また、参加ボタンを押した時のリンク先の設定方法もわからない。 %>



    <% if user_signed_in? %>
      <% if current_user.id == @touring.user_id  %>
        <div class= "ride__manage">
          <%= link_to "編集する", edit_touring_path(@touring.id), method: :get, class: "ride__btn" %>
          <%= link_to "削除する", touring_path(@touring.id) , method: :delete, class:"ride__btn" %>
        </div>
      <% end %>
    <% end %>


    <div class="liked__members">
      <% if current_user.already_liked?(@touring) %>
        <%= button_to 'いいねしました', touring_like_path(@touring), method: :delete, class:"delete__like" %>
      <% else %>
        <%= button_to 'いいね', touring_likes_path(@touring), class:"get__like" %>
      <% end %>
      <p class="like__count">いいね件数: <%= @touring.likes.count %></p>
      <p class="liked__users__list">いいねしたユーザー</p>
      <% @touring.liked_users.each do |user| %>
        <li class= 'liked__user'><%= user.nickname %></li>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<%= render "shared/second-header" %>

<div class="user__wrapper">
  <h2 class="page-heading">
    <%= "#{@user.nickname}のマイページ"%>
  </h2>
  <table class="table">
    <tbody>
      <tr>
        <th class="table__col1">アイコン</th>
        <td class="table__col2"><%= image_tag @user_icon, class:"my_icon" %></td>
      </tr>
      <tr>
        <th class="table__col1">ニックネーム</th>
        <td class="table__col2"><%= @user.nickname %></td>
      </tr>
      <tr>
        <th class="table__col1">メインエリア</th>
        <td class="table__col2"><%= "エリア" %></td>
      </tr>
      <tr>
        <th class="table__col1">ツーリングスタイル</th>
        <td class="table__col2"><%= "スタイル" %></td>
      </tr>
      <tr>
        <th class="table__col1">所有車</th>
        <td class="table__col2"><%= "所有車" %></td>
      </tr>
    </tbody>
  </table>

  <div class="user-contents">
    <h2 class="page-heading">
      <%= "#{@user.nickname}の開催"%>
    </h2>
    <div class="posts">
      <div class="user__card">
        <%= render partial: 'tourings/touring', collection: @tourings %>
      </div>
      <% if @tourings.blank? %>
        <p class = "info">開催プランはありません</p>
      <% end %>
    </div>
    <h2 class="page-heading">お気に入りのプラン</h2>
    <div class="my_liked">
      <% @user.liked_tourings.each do |touring| %>
        ・<%= touring.plan %>
        <%= link_to "by #{touring.user.nickname}", user_path(touring.user.id), class: :card__user %>
      <% end %>
      <%if @user.liked_tourings.blank? %>
        <p class = "info">登録されていません</p>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>